# API Testing
GET http://localhost:3000/

###
# GET : All Notes
GET http://localhost:3000/api/v1/notes
Content-Type: application/json

###
# GET : Note by ID
GET http://localhost:3000/api/v1/notes/1
Content-Type: application/json

###
# POST : Create Note
POST http://localhost:3000/api/v1/notes
Content-Type: application/json

{
  "title": "Note Test",
  "content": "Test test test"
}

###
# PUT : Update Note
PUT http://localhost:3000/api/v1/notes/2
Content-Type: application/json

{
  "title": "Note Test Updated",
  "content": "Test Test Test Test Test Test Test"
}

###
# DELETE : Delete Note
DELETE http://localhost:3000/api/v1/notes/1
Content-Type: application/json
